# This program says hello and asks for my name. 
print("Hello World")
print("What is your name")
myName = input()
print("It is good to meet you, " + myName)
print("How old are you, " + myName)
input()
print("Wonderful! What is yourt favorite genre of video games?")
input()
print("Interesting! I would assume your a Madden player?")
input()
print("Who is your facvorite player?")
FavoritePlayer = input()
print(FavoritePlayer + "will be the greatest of all time at some point!")
print("Wouldn't you agree?")
input()
print("I may be a computer but my favorite player is actually Josh Allen!") 
print("Think about this, Josh Allen and " + FavoritePlayer)
print("Wouldn't that be a dangerous duo?")
input()
print("Well, it was nice chatting with you!") 